test_that("is tests work", {
  expect_true(is_twomode(migraph::ison_southern_women))
  expect_false(is_directed(migraph::ison_southern_women))
  expect_false(is_weighted(migraph::ison_southern_women))
  expect_true(is_weighted(migraph::mpn_ryanair))
  expect_true(is_labelled(migraph::ison_southern_women))
  expect_false(is_complex(migraph::ison_southern_women))
  expect_true(is_graph(migraph::ison_southern_women))
  expect_true(is_migraph(migraph::ison_southern_women))
  expect_true(is_graph(migraph::ison_brandes))
  expect_false(is_directed(as_network(migraph::ison_southern_women)))
})
